# Generated by Django 3.2.3 on 2021-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('to', models.CharField(choices=[('GDL', 'Guadalajara'), ('MTY', 'Monterrey'), ('TJ', 'Tijuana'), ('SN', 'Sonora')], max_length=5)),
            ],
            options={
                'ordering': ['-date', 'hour'],
            },
        ),
    ]
