# Generated by Django 3.2.3 on 2021-05-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('to', models.CharField(choices=[('GDL', 'Guadalajara'), ('MTY', 'Monterrey'), ('TJ', 'Tijuana'), ('SN', 'Sonora')], max_length=5)),
                ('airports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports_flights', to='airports.airport')),
                ('planes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_flights', to='planes.plane')),
            ],
            options={
                'ordering': ['-date', 'hour'],
            },
        ),
    ]
