# Generated by Django 3.2.3 on 2021-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('GDL', 'Guadalajara'), ('MTY', 'Monterrey'), ('TJ', 'Tijuana'), ('SN', 'Sonora')], max_length=5)),
                ('flights', models.ManyToManyField(related_name='airports_flights', to='flights.Flight')),
                ('planes', models.ManyToManyField(related_name='airports_plane', to='planes.Plane')),
            ],
        ),
    ]
